//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.07.21 at 11:24:29 AM BRT 
//


package br.unesp.repositorio.base.xmlschema.item2collectionruler;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the br.unesp.repositorio.base.xmlschema.item2collectionruler package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _University_QNAME = new QName("http://base.repositorio.unesp.br/XMLSchema/Item2CollectionRuler", "university");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: br.unesp.repositorio.base.xmlschema.item2collectionruler
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link University }
     * 
     */
    public University createUniversity() {
        return new University();
    }

    /**
     * Create an instance of {@link Departments }
     * 
     */
    public Departments createDepartments() {
        return new Departments();
    }

    /**
     * Create an instance of {@link Campi }
     * 
     */
    public Campi createCampi() {
        return new Campi();
    }

    /**
     * Create an instance of {@link Department }
     * 
     */
    public Department createDepartment() {
        return new Department();
    }

    /**
     * Create an instance of {@link Rules }
     * 
     */
    public Rules createRules() {
        return new Rules();
    }

    /**
     * Create an instance of {@link Campus }
     * 
     */
    public Campus createCampus() {
        return new Campus();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link University }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://base.repositorio.unesp.br/XMLSchema/Item2CollectionRuler", name = "university")
    public JAXBElement<University> createUniversity(University value) {
        return new JAXBElement<University>(_University_QNAME, University.class, null, value);
    }

}
