//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.07.21 at 11:24:29 AM BRT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://base.repositorio.unesp.br/XMLSchema/Item2CollectionRuler", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package br.unesp.repositorio.base.xmlschema.item2collectionruler;
